### PR TITLE
Disable animations by default for users with reduce motion enabled

### LINKED ISSUE #33: Animations should be disabled when prefers-reduced-motion is set to reduce
It's awesome that the animations are toggle-able, but for users who have set their system preferences to reduce motion they should probably be disabled by default.

You can check for that with [the `prefers-reduced-motion: reduce` media query](https://web.dev/prefers-reduced-motion/)

### PR DESCRIPTION
**Pull request by aweary**
Resolves #33

### CODE REVIEW

**Review by zachleat — APPROVED** [review]

**Comment by zachleat** [comment]
Hmm, I like this and it seems good but it doesn’t seem to be working on the deploy preview?

https://deploy-preview-35--million-devs.netlify.app

**Comment by zachleat** [comment]
I believe you want `window.matchMedia('(prefers-reduced-motion: reduce)').matches` instead

**Review by zachleat — CHANGES_REQUESTED** [review]
Should be `window.matchMedia('(prefers-reduced-motion: reduce)').matches` I think

**Comment by aweary** [comment]
@zachleat fixed!

**Comment by zachleat** [comment]
Alright so I think your toggle logic is sound but after digging into and testing this, there is a lot more going on with how the animations are triggered and the logic with the animation toggle.

Specifically, it looks like the animation toggle logic relies on the animations being enabled on page load: https://github.com/netlify/million-devs/blob/b5250871d9fe99d2978db8ec297d707064405e5a/src/App.vue#L93

Note that `ScrollTrigger.getAll` needs those scroll triggers to be registered and enabled.

I filed a new PR with a quick workaround, we’ll see what @sdras thinks of it : #37

**Review by zachleat — CHANGES_REQUESTED** [review]
Pushed some changes to https://github.com/netlify/million-devs/pull/37 to make progress here. Moving this to Request changes so it doesn’t accidentally get merged 😅

**Pull request closed without merging**
